apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prometheus/deployment.yaml
  - grafana/deployment.yaml
  - loki/loki-statefulset.yaml
  - promtail/promtail-daemonset.yaml
