---
# Applications Kustomization
# Para serviços Kotlin, Next.js, Apollo Router, etc.
# A ser preenchido quando os serviços estiverem prontos
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
    - name: database      # Apps precisam do database
    - name: streaming     # Apps podem precisar do Kafka
  interval: 5m0s
  retryInterval: 1m0s
  timeout: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/kubernetes/flux/apps/services
  prune: true
  wait: true
  suspend: true  # Suspenso até ter serviços para deployar
