---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: unleash
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
    - name: database
  interval: 5m0s
  retryInterval: 1m0s
  timeout: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/kubernetes/flux/apps/unleash
  prune: true
  wait: true
