apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # ExternalSecret resources
  # Applied after External Secrets Operator is installed
  - service-account.yaml
  - secret-store.yaml
  - postgres-external-secret.yaml
