apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Database policies
  - postgres-allow-pgbouncer.yaml
  - pgbouncer-allow-apps.yaml
  
  # Infrastructure policies
  - vault-restrict-access.yaml
  
  # Streaming policies
  - kafka-allow-producers-consumers.yaml
